# Generated by Django 5.1.5 on 2025-05-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='images',
            field=models.ForeignKey(max_length=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.image'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='likes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.ManyToManyField(null=True, to='home.tag'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='theme',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='views',
            field=models.BigIntegerField(null=True),
        ),
    ]
