# Generated by Django 5.1.5 on 2025-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_path_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default='filemane', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='images',
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.ManyToManyField(to='home.tag'),
        ),
        migrations.AddField(
            model_name='user_post',
            name='images',
            field=models.ManyToManyField(blank=True, max_length=9, to='home.image'),
        ),
    ]
