# Generated by Django 5.1.5 on 2025-05-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_post_images_alter_user_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='images',
            field=models.ForeignKey(blank=True, max_length=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.image'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='likes',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.tag'),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_post',
            name='views',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
