# Generated by Django 5.1.5 on 2025-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=375)),
                ('theme', models.CharField(max_length=375)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ManyToManyField(null=True, to='home.image')),
            ],
        ),
    ]
