# Generated by Django 5.1.5 on 2025-06-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_image_image_file_image_filename_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default='2006-10-25 14:30:59'),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(to='home.image'),
        ),
        migrations.AddField(
            model_name='album',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/album_previews'),
        ),
        migrations.AddField(
            model_name='album',
            name='shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tag'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
